site_name: Data Creator Documentation

theme: 
  name: material

nav:
  - 'Home': index.md
  - 'Data Engineer': 
    - 'Quem é': 'Data Engineer/dataEngineer.md'
    - 'As etapas do processamento dos dados': 'Data Engineer/etlElt.md'
    - 'Databricks': 'Data Engineer/databricks.md'
    - 'Apache Spark': 'Data Engineer/apacheSpark.md'
    - 'Pipelines': 'Data Engineer/pipelines.md'
    - 'Data Lake': 'Data Engineer/dataLake.md'
    - 'Data Warehouse': 'Data Engineer/dataWarehouse.md'
    - 'Data Mart': 'Data Engineer/dataMart.md'
  - 'Data Scientist': 'Data Scientist/dataScientist.md'
  - 'Data Analyst': 'Data Analyst/dataAnalyst.md'
  - 'Appendices': 'appendices.md'
  - 'References': 'references.md'

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4