site_name: Data Creator Documentation

theme: 
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate 

nav:
  - Home: index.md
  - Data Engineer: 
    - Quem é: Data Engineer/dataEngineer.md
    - As etapas do processamento dos dados: Data Engineer/etlElt.md
    - Databricks: Data Engineer/databricks.md
    - Apache Spark: Data Engineer/apacheSpark.md
    - Pipelines: Data Engineer/pipelines.md
    - Data Lake: Data Engineer/dataLake.md
    - Data Warehouse: Data Engineer/dataWarehouse.md
    - Data Lakehouse: Data Engineer/dataLakehouse.md
    - Data Mart: Data Engineer/dataMart.md
  - Appendices: appendices.md
  - References: references.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 4
